# this binds the custom SCC "sas-cas-server" to the service account used by the CAS server
# this is needed to run the CAS server
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'system:openshift:scc:sas-cas-server'
  namespace: <your-namespace>
subjects:
  - kind: ServiceAccount
    name: sas-cas-server
    namespace: <your-namespace>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:sas-cas-server'