# this binds the nonroot SCC to the sas-programming-environment service account
# this is needed to run SAS compute sessions
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'system:openshift:scc:nonroot-v2'
  namespace: <your-namespace>
subjects:
  - kind: ServiceAccount
    name: sas-programming-environment
    namespace: <your-namespace>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:nonroot-v2'