---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  annotations:
    sas.com/ha-class: centralized
    sas.com/kustomize-base: base
  name: sas-opendistro
  namespace: $NS
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: sas-opendistro
