---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-opendistro-2-nodes-topology
patch: |-
  - op: replace
    path: /spec/nodes/0/replicas
    value: 2
target:
  kind: OpenDistroCluster
  name: sas-opendistro
