apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-opendistro-run-user-transformer
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/securityContext
    value: {}
  - op: add
    path: /spec/template/spec/containers/0/securityContext/runAsUser
    value: 1000
  - op: replace
    path: /spec/template/spec/serviceAccountName
    value: sas-programming-environment
target:
  kind: OpenDistroCluster
